"""Build the stock-screening table from the SEC's bulk Company Facts archive.

Resumable download, parse and derive in one importable module, so the MCP tool
``refresh_screening_data`` can run it on a hosted server and ``python -m
agent.sec_refresh`` can run the same code from a shell.

The archive (https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip)
is ~1.4 GB and regenerated by the SEC nightly; parsing its ~20,000 filer files
takes minutes. A refresh therefore runs in a background thread: ``start()``
returns immediately and ``status()`` reports progress. On a hosted server the
result lives in disposable storage, so the finished parquet and its metadata
are also uploaded to the private dataset named by ``HF_DATA_REPO`` when the
configured token (``HF_TOKEN``, or ``HF_WRITE_TOKEN`` if an operator keeps them
separate) has write access -- that is what makes a refresh survive the next cold
start.

Guards, because the public endpoint is unauthenticated:
  * single-flight: a second start while one runs just returns the status;
  * rate limit: at most one refresh per ``MIN_INTERVAL_HOURS``;
  * freshness: if the SEC archive has not changed since the last build, nothing
    is downloaded (``force=True`` overrides this, not the rate limit);
  * operator passphrase: when ``REFRESH_TOKEN`` is set, ``start`` requires it, and
    anything shaped like a Hugging Face token is rejected outright so the real
    token is never sent to this tool by mistake.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import threading
import time
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import requests

from .config import DATA
from .sec import INCOME_STATEMENT, UA, ticker_map

URL = "https://www.sec.gov/Archives/edgar/daily-index/xbrl/companyfacts.zip"
ZIP = DATA / "sec" / "companyfacts.zip"
RAW = DATA / "sec" / "_universe_raw.pkl"
# The dataset mirrors the data directory, so a hosted server downloads these to
# exactly where it would have built them.
DATASET_PREFIX = "live_cache/universe"
OUT = DATA / DATASET_PREFIX / "sec_universe.parquet"
META = DATA / DATASET_PREFIX / "sec_universe.meta.json"

MIN_INTERVAL_HOURS = float(os.getenv("REFRESH_MIN_INTERVAL_HOURS", "20"))

WANT = {
    "revenue": INCOME_STATEMENT[0][1],
    "gross_profit": ["GrossProfit"],
    "operating_income": ["OperatingIncomeLoss"],
    "net_income": ["NetIncomeLoss", "ProfitLoss"],
    "assets": ["Assets"],
    "current_assets": ["AssetsCurrent"],
    "liabilities": ["Liabilities"],
    "current_liabilities": ["LiabilitiesCurrent"],
    "equity": ["StockholdersEquity",
               "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"],
    "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebt"],
    "cash": ["CashAndCashEquivalentsAtCarryingValue"],
    "ocf": ["NetCashProvidedByUsedInOperatingActivities",
            "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations"],
    "capex": ["PaymentsToAcquirePropertyPlantAndEquipment"],
}
_DURATION = {"revenue", "gross_profit", "operating_income", "net_income", "ocf", "capex"}

# The largest US public float on record is NVIDIA's ~$4tn. An order of magnitude
# beyond that is a filing error, not a company.
MAX_PLAUSIBLE_FLOAT = 2e13


# ----------------------------------------------------------------- remote ---
def remote_info() -> dict:
    """Content-Length / Last-Modified / ETag of the SEC archive, or {} offline."""
    try:
        r = requests.head(URL, headers=UA, timeout=60, allow_redirects=True)
        r.raise_for_status()
        h = r.headers
        return {"content_length": int(h.get("Content-Length", 0) or 0),
                "last_modified": h.get("Last-Modified", ""),
                "etag": h.get("ETag", "")}
    except Exception as e:
        return {"error": f"{type(e).__name__}: {e}"}


def read_meta() -> dict:
    if META.exists():
        try:
            return json.loads(META.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}


def is_current(remote: dict | None = None) -> tuple[bool, str]:
    """Does the table on disk already reflect the SEC archive as it is now?"""
    meta = read_meta()
    if not OUT.exists() or not meta:
        return False, "no screening table (or no metadata) on this server"
    remote = remote if remote is not None else remote_info()
    if remote.get("error"):
        return False, f"could not reach sec.gov to check: {remote['error']}"
    same_lm = remote.get("last_modified") and remote["last_modified"] == meta.get("source_last_modified")
    same_etag = remote.get("etag") and remote["etag"] == meta.get("source_etag")
    if same_lm or same_etag:
        return True, (f"table built {meta.get('built_at_utc')} from the archive dated "
                      f"{meta.get('source_last_modified')}, which is still the current one")
    return False, (f"SEC archive is dated {remote.get('last_modified')}; table was built "
                   f"from {meta.get('source_last_modified') or 'an unknown archive date'}")


# --------------------------------------------------------------- download ---
def _human(n: float) -> str:
    return f"{n / 1e9:.2f} GB" if n >= 1e9 else f"{n / 1e6:.0f} MB"


def download(progress=lambda msg: None, chunk_mb: int = 4, max_attempts: int = 40) -> dict:
    """Fetch the archive with HTTP-Range resume. Returns remote_info()."""
    ZIP.parent.mkdir(parents=True, exist_ok=True)
    remote = remote_info()
    if remote.get("error"):
        raise RuntimeError(f"sec.gov unreachable: {remote['error']}")
    total = remote.get("content_length", 0)
    have = ZIP.stat().st_size if ZIP.exists() else 0
    if total and have == total and _zip_ok():
        progress(f"archive already on disk and complete ({_human(total)}); skipping download")
        return remote
    if have > total:
        ZIP.unlink(missing_ok=True)
        have = 0

    attempt, last_report = 0, time.time()
    while attempt < max_attempts:
        have = ZIP.stat().st_size if ZIP.exists() else 0
        if total and have >= total:
            break
        headers = dict(UA)
        if have:
            headers["Range"] = f"bytes={have}-"
        try:
            with requests.get(URL, headers=headers, stream=True, timeout=120) as r:
                if have and r.status_code not in (206, 416):
                    ZIP.unlink(missing_ok=True)   # server ignored Range: restart clean
                    continue
                if r.status_code == 416:
                    break
                r.raise_for_status()
                with open(ZIP, "ab" if have else "wb") as f:
                    for block in r.iter_content(chunk_size=chunk_mb * 1024 * 1024):
                        f.write(block)
                        if time.time() - last_report > 15:
                            got = ZIP.stat().st_size
                            pct = f" ({got / total:.0%})" if total else ""
                            progress(f"downloading {_human(got)}{pct}")
                            last_report = time.time()
        except Exception as e:
            attempt += 1
            progress(f"download interrupted ({type(e).__name__}); retry {attempt}")
            time.sleep(min(2 ** min(attempt, 5), 30))
            continue
        have = ZIP.stat().st_size if ZIP.exists() else 0
        if not total or have >= total:
            break

    if not _zip_ok():
        raise RuntimeError("downloaded archive does not open as a zip; will resume on next run")
    progress(f"download complete ({_human(ZIP.stat().st_size)})")
    return remote


def _zip_ok() -> bool:
    try:
        with zipfile.ZipFile(ZIP) as z:
            return bool(z.namelist())
    except Exception:
        return False


# ------------------------------------------------------------------ parse ---
def _latest(node: dict, want_duration: bool):
    """Most recent reported USD value for one concept. Duration items need an
    annual period (330-400 days); instant items must have no start date."""
    best = None
    today = dt.date.today()
    for unit, pts in (node.get("units") or {}).items():
        if unit != "USD":
            continue
        for p in pts:
            end, val = p.get("end"), p.get("val")
            if not end or val is None:
                continue
            try:
                end_date = dt.date.fromisoformat(end)
            except ValueError:
                continue
            if end_date > today:            # mistyped contexts like 2201-10-31
                continue
            start = p.get("start")
            if want_duration:
                if not start:
                    continue
                try:
                    d = (end_date - dt.date.fromisoformat(start)).days
                except ValueError:
                    continue
                if not (330 <= d <= 400):
                    continue
            elif start:
                continue
            if best is None or end > best[0]:
                best = (end, val)
    return best


def _valid_date_on_or_before(value: str, cutoff: dt.date) -> bool:
    try:
        return dt.date.fromisoformat(value) <= cutoff
    except (TypeError, ValueError):
        return False


def _public_float(node: dict):
    """Latest USD public float, rejecting the filer's own unit errors (a 1e3/1e6
    jump against the previous filing, or a value beyond any real company)."""
    today = dt.date.today()
    pts = sorted({(p["end"], p["val"]) for p in (node.get("units", {}).get("USD") or [])
                  if p.get("end") and p.get("val") is not None and p["val"] > 0
                  and _valid_date_on_or_before(p["end"], today)})
    if not pts:
        return None
    suspect = False
    for i in range(len(pts) - 1, -1, -1):
        end, val = pts[i]
        if val > MAX_PLAUSIBLE_FLOAT:
            suspect = True
            continue
        if i > 0:
            prev = pts[i - 1][1]
            if prev and val / prev > 50:
                suspect = True
                continue
        return val, end, suspect
    return None


def row_for(facts: dict) -> dict | None:
    gaap = facts.get("facts", {}).get("us-gaap", {})
    dei = facts.get("facts", {}).get("dei", {})
    if not gaap:
        return None
    rec: dict = {"cik": facts.get("cik"), "company_name": facts.get("entityName")}
    for name, tags in WANT.items():
        # Most RECENT value across candidate tags, not first tag with data: filers
        # migrate between concepts, and a stale tag would pair years-old revenue with
        # current profit and produce an impossible margin.
        best = None
        for tag in tags:
            node = gaap.get(tag)
            if not node:
                continue
            got = _latest(node, name in _DURATION)
            if got and (best is None or got[0] > best[0]):
                best = got
        if best:
            rec[name] = best[1]
            rec[name + "_end"] = best[0]
            rec["as_of"] = max(rec.get("as_of", ""), best[0])
    pf = dei.get("EntityPublicFloat")
    if pf:
        got = _public_float(pf)
        if got:
            rec["public_float_usd"], rec["float_as_of"], rec["float_suspect"] = got
    return rec if rec.get("revenue") or rec.get("assets") else None


def parse_archive(progress=lambda msg: None) -> tuple[pd.DataFrame, int, int]:
    rows, skipped = [], 0
    with zipfile.ZipFile(ZIP) as z:
        names = [n for n in z.namelist() if n.endswith(".json")]
        total = len(names)
        progress(f"parsing {total:,} filers")
        for i, n in enumerate(names, 1):
            try:
                r = row_for(json.loads(z.read(n)))
            except Exception:
                r = None
            if r:
                rows.append(r)
            else:
                skipped += 1
            if i % 2500 == 0:
                progress(f"parsed {i:,}/{total:,} filers, kept {len(rows):,}")
    df = pd.DataFrame(rows)
    RAW.parent.mkdir(parents=True, exist_ok=True)
    df.to_pickle(RAW)                    # checkpoint: the parse is the slow part
    return df, total, skipped


# ----------------------------------------------------------------- derive ---
def _sanitize_future_periods(df: pd.DataFrame) -> tuple[pd.DataFrame, int]:
    today = pd.Timestamp(dt.date.today())
    removed = 0
    end_columns = []
    for value_column in WANT:
        end_column = value_column + "_end"
        if end_column not in df.columns:
            continue
        bad = pd.to_datetime(df[end_column], errors="coerce") > today
        if bad.any():
            removed += int(bad.sum())
            df.loc[bad, value_column] = np.nan
            df.loc[bad, end_column] = pd.NA
        end_columns.append(end_column)
    if "float_as_of" in df.columns:
        bad = pd.to_datetime(df["float_as_of"], errors="coerce") > today
        if bad.any():
            removed += int(bad.sum())
            df.loc[bad, "public_float_usd"] = np.nan
            df.loc[bad, "float_as_of"] = pd.NA
            df.loc[bad, "float_suspect"] = True
    if end_columns:
        dates = pd.concat([pd.to_datetime(df[c], errors="coerce").rename(c)
                           for c in end_columns], axis=1)
        df["as_of"] = dates.max(axis=1).dt.strftime("%Y-%m-%d")
    return df, removed


def derive(df: pd.DataFrame) -> pd.DataFrame:
    def safe(a, b):
        return (a / b).replace([np.inf, -np.inf], np.nan).astype("float64")
    df["net_margin_pct"] = (safe(df["net_income"], df["revenue"]) * 100).round(2)
    df["operating_margin_pct"] = (safe(df["operating_income"], df["revenue"]) * 100).round(2)
    df["gross_margin_pct"] = (safe(df["gross_profit"], df["revenue"]) * 100).round(2)
    df["roe_pct"] = (safe(df["net_income"], df["equity"]) * 100).round(2)
    df["roa_pct"] = (safe(df["net_income"], df["assets"]) * 100).round(2)
    df["debt_equity"] = safe(df["long_term_debt"], df["equity"]).round(3)
    df["current_ratio"] = safe(df["current_assets"], df["current_liabilities"]).round(2)
    df["fcf"] = df["ocf"] - df["capex"].fillna(0)
    df["fcf_margin_pct"] = (safe(df["fcf"], df["revenue"]) * 100).round(2)
    df.loc[df["equity"] <= 0, "roe_pct"] = np.nan   # negative equity: ROE meaningless
    for c in ("revenue", "net_income", "assets", "equity", "public_float_usd", "fcf"):
        df[c + "_musd"] = (pd.to_numeric(df[c], errors="coerce") / 1e6).round(1)
    return df


def _sanity_check_float(df: pd.DataFrame) -> tuple[pd.DataFrame, int]:
    """Blank public floats the company's own financials contradict (P/E > 2000,
    P/S > 1000, or > 500x assets for loss-making filers): filer unit errors."""
    f = pd.to_numeric(df.get("public_float_usd"), errors="coerce")
    rev = pd.to_numeric(df.get("revenue"), errors="coerce")
    ni = pd.to_numeric(df.get("net_income"), errors="coerce")
    assets = pd.to_numeric(df.get("assets"), errors="coerce")
    bad = pd.Series(False, index=df.index)
    bad |= (ni > 0) & (f / ni > 2000)
    bad |= (rev > 0) & (f / rev > 1000)
    bad |= ((rev.isna() | (rev <= 0)) & (assets > 0) & (f / assets > 500))
    bad = bad.fillna(False)
    n = int(bad.sum())
    if n:
        df.loc[bad, "float_suspect"] = True
        df.loc[bad, "public_float_usd"] = np.nan
    return df, n


def _symbol_map() -> dict[int, str]:
    """CIK -> one ticker. A CIK can carry several (JPM, JPM-PC, ...); prefer the
    common stock: no hyphen or suffix, then the shortest."""
    by_cik: dict[int, list[str]] = {}
    for tick, c in ticker_map().items():
        by_cik.setdefault(c, []).append(tick)
    return {c: sorted(ts, key=lambda s: ("-" in s or "." in s, len(s), s))[0]
            for c, ts in by_cik.items()}


def finish(df: pd.DataFrame, *, archive_filers: int, remote: dict,
           progress=lambda msg: None) -> dict:
    df["cik"] = pd.to_numeric(df["cik"], errors="coerce").astype("Int64")
    for c in list(WANT) + ["public_float_usd"]:
        if c not in df.columns:
            df[c] = pd.NA
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df, future_removed = _sanitize_future_periods(df)
    df = derive(df)
    df, floats_blanked = _sanity_check_float(df)
    inv = _symbol_map()
    if not inv:
        raise RuntimeError("SEC ticker map unavailable; cannot label rows with symbols "
                           "(is SEC_USER_AGENT set?)")
    df["symbol"] = df["cik"].map(inv)
    df = df.sort_values("public_float_usd", ascending=False).reset_index(drop=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(OUT, index=False)

    ao = pd.to_datetime(df["as_of"], errors="coerce")
    meta = {
        "source": "SEC EDGAR bulk Company Facts",
        "source_url": URL,
        "source_last_modified": remote.get("last_modified", ""),
        "source_etag": remote.get("etag", ""),
        "built_at_utc": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "built_by": "agent.sec_refresh",
        "archive_sha256": _sha256(ZIP),
        "parquet_sha256": _sha256(OUT),
        "archive_filers": int(archive_filers),
        "usable_filers": int(len(df)),
        "ticker_mapped_rows": int(df["symbol"].notna().sum()),
        "latest_valid_as_of": ao.max().date().isoformat() if ao.notna().any() else None,
        "schema_columns": int(df.shape[1]),
        "future_dated_values_removed": int(future_removed),
        "invalid_public_float_values_blanked": int(floats_blanked),
        "ticker_selection": "one symbol per CIK, common stock preferred",
        "validation": {
            "future_dated_rows": int((ao > pd.Timestamp.today()).sum()),
            "infinite_numeric_values": int((df.select_dtypes("number").abs() == np.inf).sum().sum()),
        },
    }
    META.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    progress(f"wrote {OUT.name}: {len(df):,} filers, {meta['ticker_mapped_rows']:,} with tickers, "
             f"latest period {meta['latest_valid_as_of']}")
    return meta


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 24), b""):
            h.update(chunk)
    return h.hexdigest()


def build(progress=lambda msg: None, remote: dict | None = None) -> dict:
    """Parse the archive on disk into the table. Resumes from the raw checkpoint
    when a previous parse finished but a later step failed."""
    if not ZIP.exists():
        raise RuntimeError(f"archive missing at {ZIP}; download first")
    remote = remote or remote_info()
    with zipfile.ZipFile(ZIP) as z:
        archive_filers = sum(1 for n in z.namelist() if n.endswith(".json"))
    if RAW.exists() and RAW.stat().st_mtime >= ZIP.stat().st_mtime:
        progress("resuming from the parsed checkpoint")
        df = pd.read_pickle(RAW)
    else:
        df, archive_filers, _ = parse_archive(progress)
    meta = finish(df, archive_filers=archive_filers, remote=remote, progress=progress)
    RAW.unlink(missing_ok=True)
    return meta


# ---------------------------------------------------------------- persist ---
def persist(progress=lambda msg: None) -> str | None:
    """Upload the table and metadata to the private dataset, if a write token
    is configured. Returns a note describing what happened."""
    # One token is enough: the server's HF_TOKEN, if it carries write access to the
    # dataset, is used for the upload. HF_WRITE_TOKEN exists only for operators who
    # prefer to keep the runtime's read token separate from a write one.
    token = (os.getenv("HF_WRITE_TOKEN", "").strip() or os.getenv("HF_TOKEN", "").strip())
    repo = os.getenv("HF_DATA_REPO", "").strip()
    if not token or not repo:
        return ("not uploaded: HF_DATA_REPO and HF_TOKEN are not both configured, so "
                "this table lives in the server's local storage only")
    try:
        from huggingface_hub import CommitOperationAdd, HfApi
        api = HfApi(token=token)
        ops = [CommitOperationAdd(path_in_repo=f"{DATASET_PREFIX}/{p.name}", path_or_fileobj=str(p))
               for p in (OUT, META)]
        api.create_commit(repo_id=repo, repo_type="dataset", operations=ops,
                          commit_message=f"refresh screening table from SEC archive dated "
                                         f"{read_meta().get('source_last_modified', '?')}")
        progress(f"uploaded {OUT.name} and {META.name} to {repo}")
        return f"uploaded to {repo}; the next cold start hydrates this table"
    except Exception as e:
        return (f"upload failed ({type(e).__name__}: {e}); the table is refreshed on this "
                f"server only. If the error is a 403, the server's HF_TOKEN is read-only -- "
                f"give it write access to the dataset for refreshes to persist")


# -------------------------------------------------------------------- job ---
_LOCK = threading.Lock()
STATE: dict = {"running": False, "stage": "idle", "log": [], "started_at": None,
               "finished_at": None, "error": None, "result": None, "persist": None}


def _log(msg: str) -> None:
    STATE["stage"] = msg
    STATE["log"].append(f"{dt.datetime.now(dt.timezone.utc).strftime('%H:%M:%SZ')} {msg}")
    STATE["log"] = STATE["log"][-40:]


def _run(force: bool) -> None:
    try:
        remote = remote_info()
        current, why = is_current(remote)
        if current and not force:
            _log(f"nothing to do: {why}")
            STATE["result"] = read_meta()
            return
        remote = download(_log)
        STATE["result"] = build(_log, remote=remote)
        STATE["persist"] = persist(_log)
        _log("done")
    except Exception as e:
        STATE["error"] = f"{type(e).__name__}: {e}"
        _log(f"failed: {STATE['error']}")
    finally:
        STATE["running"] = False
        STATE["finished_at"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def start(force: bool = False, passphrase: str | None = None) -> dict:
    """Begin a refresh in the background. Returns status(), whose ``accepted``
    key says whether this call started one."""
    given = (passphrase or "").strip()
    if given.startswith("hf_"):
        # Guard against the obvious mistake: the passphrase is the operator's
        # REFRESH_TOKEN secret, never a Hugging Face access token.
        return {**status(), "accepted": False,
                "reason": ("that looks like a Hugging Face access token. The refresh "
                           "passphrase is the REFRESH_TOKEN value set on the server, not an "
                           "hf_ token -- do not send HF tokens to this tool")}
    required = os.getenv("REFRESH_TOKEN", "").strip()
    if required and given != required:
        return {**status(), "accepted": False,
                "reason": ("this server only refreshes for its operator; pass the passphrase "
                           "set as the server's REFRESH_TOKEN")}
    with _LOCK:
        if STATE["running"]:
            return {**status(), "accepted": False, "reason": "a refresh is already running"}
        built = read_meta().get("built_at_utc")
        if built:
            try:
                age_h = (dt.datetime.now(dt.timezone.utc)
                         - dt.datetime.strptime(built, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)
                         ).total_seconds() / 3600
            except ValueError:
                age_h = float("inf")
            if age_h < MIN_INTERVAL_HOURS:
                return {**status(), "accepted": False,
                        "reason": (f"table was built {age_h:.1f} h ago; refreshes are limited "
                                   f"to one per {MIN_INTERVAL_HOURS:g} h (SEC regenerates the "
                                   f"archive nightly)")}
        STATE.update({"running": True, "log": [], "error": None, "result": None, "persist": None,
                      "started_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
                      "finished_at": None})
        _log("starting" + (" (forced)" if force else ""))
        threading.Thread(target=_run, args=(force,), name="sec-refresh", daemon=True).start()
    return {**status(), "accepted": True}


def status() -> dict:
    meta = read_meta()
    out = {
        "running": STATE["running"],
        "stage": STATE["stage"],
        "started_at": STATE["started_at"],
        "finished_at": STATE["finished_at"],
        "error": STATE["error"],
        "persist": STATE["persist"],
        "recent_log": STATE["log"][-8:],
        "table_on_server": {
            "exists": OUT.exists(),
            "built_at_utc": meta.get("built_at_utc"),
            "source_archive_dated": meta.get("source_last_modified"),
            "latest_period_end": meta.get("latest_valid_as_of"),
            "filers": meta.get("usable_filers"),
            "with_ticker": meta.get("ticker_mapped_rows"),
        },
        "persistence": ("a dataset and token are configured: a finished refresh is uploaded "
                        "(needs write access on it; the persist field reports the outcome)"
                        if (os.getenv("HF_DATA_REPO", "").strip()
                            and (os.getenv("HF_WRITE_TOKEN", "").strip()
                                 or os.getenv("HF_TOKEN", "").strip()))
                        else "no dataset configured: the table is kept in local storage only"),
        "protected": bool(os.getenv("REFRESH_TOKEN", "").strip()),
    }
    if not STATE["running"]:
        current, why = is_current()
        out["up_to_date"] = current
        out["freshness"] = why
    return out


# -------------------------------------------------------------------- cli ---
def _main(argv: list[str] | None = None) -> int:
    """Run a refresh from a shell, synchronously, printing progress.

        python -m agent.sec_refresh            # download if changed, build, upload
        python -m agent.sec_refresh --force    # rebuild even if the archive is unchanged
        python -m agent.sec_refresh --status   # freshness only, no download

    Needs SEC_USER_AGENT (contact-bearing) and, for the upload, HF_DATA_REPO plus
    an HF_TOKEN with write access to it. A hosted server picks the uploaded table
    up at its next cold start; restart it to force that.
    """
    import argparse
    ap = argparse.ArgumentParser(prog="python -m agent.sec_refresh")
    ap.add_argument("--force", action="store_true", help="rebuild even if the SEC archive is unchanged")
    ap.add_argument("--status", action="store_true", help="report freshness and exit")
    ap.add_argument("--no-upload", action="store_true", help="build only; do not upload to the dataset")
    a = ap.parse_args(argv)
    say = lambda m: print(m, flush=True)
    if a.status:
        print(json.dumps(status(), indent=2))
        return 0
    remote = remote_info()
    current, why = is_current(remote)
    if current and not a.force:
        say(f"nothing to do: {why}")
        return 0
    remote = download(say)
    meta = build(say, remote=remote)
    say(f"built {meta['usable_filers']:,} filers, {meta['ticker_mapped_rows']:,} with tickers, "
        f"latest period {meta['latest_valid_as_of']}")
    if not a.no_upload:
        say(persist(say))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
